<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Title>OpenccJieba C API Interop Library</Title>
        <Authors>laisuk</Authors>
        <Description>opencc-jieba-rs Rust based C API .NET interop library for Chinese text conversion and segmentation between Traditional and Simplified Chinese</Description>
        <PackageTags>opencc;chinese;jieba;traditional;simplified;capi</PackageTags>
        <Copyright>laisuk</Copyright>
        <PackageProjectUrl>https://github.com/laisuk/OpenccJiebaLib</PackageProjectUrl>
        <RepositoryUrl>https://github.com/laisuk/OpenccJiebaLib</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
        <FileVersion>1.1.0.0</FileVersion>
        <Version>1.1.0</Version>
        <PackageReleaseNotes>v1.1.0
Update opencc-jieba-rs C API natives to v0.7.1
        </PackageReleaseNotes>
    </PropertyGroup>

    <!-- Include README and LICENSE at package root -->
    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\"/>
        <None Include="..\LICENSE" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <!-- Pack native assets to the same paths; do NOT copy on build -->
    <ItemGroup>
        <None Include="runtimes\win-x64\native\opencc_jieba_capi.dll"
              Pack="true"
              PackagePath="runtimes/win-x64/native/"/>
        <None Include="runtimes\linux-x64\native\libopencc_jieba_capi.so"
              Pack="true"
              PackagePath="runtimes/linux-x64/native/"/>
        <None Include="runtimes\osx-arm64\native\libopencc_jieba_capi.dylib"
              Pack="true"
              PackagePath="runtimes/osx-arm64/native/"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Memory" Version="4.6.3"/>
    </ItemGroup>

</Project>
